Eception and validation
BoShMan78/book-store-v2 pull request #12
Opened 2024-06-18 13:11 UTC by BoShMan78

2024-06-18 17:02 UTC, Vasul-Pankiv requested changes

2024-06-18 17:02 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/bookstorev2/dto/CreateBookRequestDto.java
> +    @NotNull
```suggestion
    @NotBlank
```

2024-06-18 17:02 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/bookstorev2/dto/CreateBookRequestDto.java
> +    @NotNull
same here

2024-06-19 06:57 UTC, Elena-Bruyako requested changes
Good job! Let's fix some comments

2024-06-19 06:57 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/dto/CreateBookRequestDto.java
> +    @NotNull
```suggestion
    @NotBlank
```

2024-06-19 06:57 UTC, Elena-Bruyako commented on pom.xml
> +        <dependency>
It's better to add this 
```suggestion
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
```

2024-06-19 06:57 UTC, Elena-Bruyako commented on pom.xml
> +            <artifactId>hibernate-validator</artifactId>
remove

2024-06-19 06:57 UTC, Elena-Bruyako commented on pom.xml
> +            <artifactId>hibernate-validator-annotation-processor</artifactId>
remove

2024-06-20 14:47 UTC, Vasul-Pankiv approved these changes

2024-06-22 10:40 UTC, merged