User,UserRegistrationRequestDto, UserResponseDto, UserMapper, UserRep…
BoShMan78/book-store-v2 pull request #15
Opened 2024-07-11 15:46 UTC by BoShMan78

…ository, UserService, AuthenticationController were added.

2024-07-12 06:21 UTC, Elena-Bruyako requested changes
see pr

2024-07-12 06:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/model/User.java
> +@NoArgsConstructor
```suggestion
```

2024-07-12 06:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/service/UserServiceImpl.java
> +        User user = userMapper.toModel(requestDto);
we need to check if uses existsByEmail first

2024-07-12 06:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/validation/UniqueEmailValidator.java
> +public class UniqueEmailValidator implements ConstraintValidator<UniqueEmail, String> {
remove

2024-07-12 06:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/validation/UniqueEmail.java
> +public @interface UniqueEmail {
remove,  redundant

2024-07-12 06:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/dto/UserRegistrationRequestDto.java
> +    @UniqueEmail
```suggestion
```

If you would like to add custom annotation, use some pattern to check valid email

2024-07-12 08:47 UTC, Elena-Bruyako requested changes
see comments

2024-07-12 08:47 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/dto/UserRegistrationRequestDto.java
> +    @Email(message = "Email is not valid",
Suggestion , test this pattern if it works correctly. Also, you can create your custom validation like for passwords, but with pattern

2024-07-12 08:47 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/exception/CustomGlobalExceptionHandler.java
> +        body.put("status: ", HttpStatus.BAD_REQUEST.value());
```suggestion
        body.put("status: ", HttpStatus.CONFLICT.value());
```

2024-07-12 08:47 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, HttpStatus.BAD_REQUEST);
same

2024-07-13 07:14 UTC, Elena-Bruyako requested changes
see pr

2024-07-13 07:14 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/dto/UserRegistrationRequestDto.java
> +    //Min 1 uppercase letter
remove commented code

2024-07-13 18:34 UTC, sarakhmen approved these changes

2024-07-14 12:50 UTC, merged