AuthenticationController, AuthenticationService: login return JWT token
BoShMan78/book-store-v2 pull request #17
Opened 2024-08-05 13:37 UTC by BoShMan78

JwtAuthenticationFilter, JwtUtil, OpenApiConfig, UserLoginResponseDto added

2024-08-05 14:07 UTC, Elena-Bruyako requested changes
see comments

2024-08-05 14:07 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/config/OpenApiConfig.java
> +                .components(new Components().addSecuritySchemes("BearerAuth",
Create constants for String BearerAuth and etc

2024-08-05 14:07 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
Use String constant for Authorization from HttpHeaders

2024-08-05 14:07 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer")) {
create constant for "Bearer " (don't forget whitespace)

2024-08-05 14:07 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
use constant above and length() instead of 7

2024-08-06 08:56 UTC, Elena-Bruyako requested changes
see comments

2024-08-06 08:56 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader(AUTHORIZATION);
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

2024-08-06 08:56 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/security/JwtAuthenticationFilter.java
> +    public static final String AUTHORIZATION = "Authorization";
```suggestion
```

2024-08-06 08:56 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/security/JwtAuthenticationFilter.java
> +    public static final int TOKEN_INDEX = 7;
```suggestion
```

2024-08-06 08:56 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/security/JwtAuthenticationFilter.java
> +    public static final String BEARER = "Bearer";
```suggestion
    public static final String TOKEN_HEADER = "Bearer ";
```

2024-08-06 08:56 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(TOKEN_INDEX);
```suggestion
        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith(TOKEN_HEADER)) {
            return bearerToken.substring(TOKEN_HEADER.length());
```

2024-08-08 14:31 UTC, okuzan approved these changes

2024-08-09 07:51 UTC, merged