Shooping cart implemented:
BoShMan78/book-store-v2 pull request #19
Opened 2024-09-01 16:05 UTC by BoShMan78

Liquibase: shopping-cart-table, cart-item-table schemas created

ShoppingCartController, ShoppingCartService, ShoppingCartRepository, ShoppingCartMapper added

ShoppingCart, ShoppingCartDto,added

CartItem, CartItemAddBookResponseDto, CartItemDto, CartItemUpdateDto added

CartItemRepository added

2024-09-02 12:49 UTC, Elena-Bruyako requested changes
see comments

2024-09-02 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/controller/ShoppingCartController.java
> +@RequestMapping("/api/cart")
```suggestion
@RequestMapping("/cart")
```

add `server.servlet.context-path=/api` to application.properties

2024-09-02 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/controller/ShoppingCartController.java
> +    public void updateCartItem(@PathVariable @Positive Long cartItemId,
```suggestion
    public ShoppingCartDto updateCartItem(@PathVariable @Positive Long cartItemId,
```

2024-09-02 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/controller/ShoppingCartController.java
> +@RestController
```suggestion
@RestController
@Validated
```

2024-09-02 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/controller/ShoppingCartController.java
> +    public CartItemAddBookResponseDto addBookToShoppingCart(
```suggestion
    public ShoppingCartDto addBookToShoppingCart(
```

2024-09-02 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/controller/ShoppingCartController.java
> +            @RequestBody @Valid AddToShoppingCartDto dto,
```suggestion
            @RequestBody @Valid CartItemRequestDto cartItemDto,
```

2024-09-02 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/dto/cart/item/CartItemUpdateDto.java
> +        @NonNull
```suggestion
```

int can't be null

2024-09-02 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/model/ShoppingCart.java
> +@Table(name = "shopping_cart")
```suggestion
@Table(name = "shopping_carts")
```

2024-09-02 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/model/CartItem.java
> +@Table(name = "cart_item")
```suggestion
@Table(name = "cart_items")
```

2024-09-02 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/model/User.java
> +    private ShoppingCart shoppingCart;
```suggestion
```

2024-09-02 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/service/ShoppingCartServiceImpl.java
> +    @Override
Check where is Transactional needed

2024-09-02 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/service/ShoppingCartServiceImpl.java
> +    @Transactional
```suggestion
```

2024-09-02 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstorev2/service/ShoppingCartServiceImpl.java
> +                .orElseGet(() -> createShoppingCartForUser(user));
you create shop cart during the registration, if you can't find shop cart for user - throw exception

2024-09-03 20:17 UTC, sarakhmen approved these changes

2024-09-04 14:07 UTC, merged